<h4> Import necessary module

In [1]:
import pandas as pd

from ipyleaflet import Map, basemaps, basemap_to_tiles, LayersControl, AwesomeIcon, Marker, CircleMarker, Popup, LegendControl

from ipywidgets import HTML, Layout

<h4> Reading Station ID Inventatory file

In [2]:
# First 3 lines of the csv files must be discarded
rows2skip = list(range(0,3))

stnID_df = pd.read_csv('../data/ECCC/Station_Inventory_EN.csv', skiprows=rows2skip)
stnID_df

,Name,Province,Climate ID,Station ID,WMO ID,TC ID,Latitude (Decimal Degrees),Longitude (Decimal Degrees),Latitude,Longitude,Elevation (m),First Year,Last Year,HLY First Year,HLY Last Year,DLY First Year,DLY Last Year,MLY First Year,MLY Last Year
0,ACTIVE PASS,BRITISH COLUMBIA,1010066,14,NaN,NaN,48.87,-123.28,485200000,-1231700000,4.0,1984,1996,NaN,NaN,1984.0,1996.0,1984.0,1996.0
1,ALBERT HEAD,BRITISH COLUMBIA,1010235,15,NaN,NaN,48.40,-123.48,482400000,-1232900000,17.0,1971,1995,NaN,NaN,1971.0,1995.0,1971.0,1995.0
2,BAMBERTON OCEAN CEMENT,BRITISH COLUMBIA,1010595,16,NaN,NaN,48.58,-123.52,483500000,-1233100000,85.3,1961,1980,NaN,NaN,1961.0,1980.0,1961.0,1980.0
3,BEAR CREEK,BRITISH COLUMBIA,1010720,17,NaN,NaN,48.50,-124.00,483000000,-1240000000,350.5,1910,1971,NaN,NaN,1910.0,1971.0,1910.0,1971.0
4,BEAVER LAKE,BRITISH COLUMBIA,1010774,18,NaN,NaN,48.50,-123.35,483000000,-1232100000,61.0,1894,1952,NaN,NaN,1894.0,1952.0,1894.0,1952.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8809,WEST ST MODESTE,NEWFOUNDLAND,8504216,6803,NaN,NaN,51.60,-56.70,513600000,-564200000,12.2,1990,2002,NaN,NaN,1990.0,2002.0,1990.0,2002.0
8810,WEST ST MODESTE,NEWFOUNDLAND,8504217,6804,NaN,NaN,51.58,-56.72,513500000,-564300000,15.2,1984,1987,NaN,NaN,1984.0,1987.0,1984.0,1987.0
8811,CHURCHILL FALLS,NEWFOUNDLAND,850A131,6940,NaN,NaN,53.53,-63.97,533200000,-635800000,488.5,1993,1998,NaN,NaN,1993.0,1998.0,1993.0,1998.0
8812,MAKKOVIK (AUT),NEWFOUNDLAND,850B5HR,9025,NaN,NaN,55.08,-59.17,550500000,-591000000,71.3,1985,1986,1985.0,1986.0,NaN,NaN,NaN,NaN
8813,MARY'S HARBOUR,NEWFOUNDLAND,850B5R1,10227,71339.0,YMH,52.30,-55.83,521813000,-554957000,11.6,1992,2014,1994.0,2014.0,1992.0,2013.0,2005.0,2007.0

<h4> Keeping the station for the Quebec Province only

In [3]:
stnID_df =stnID_df[stnID_df['Province'] == 'Quebec'.upper()]
stnID_df

,Name,Province,Climate ID,Station ID,WMO ID,TC ID,Latitude (Decimal Degrees),Longitude (Decimal Degrees),Latitude,Longitude,Elevation (m),First Year,Last Year,HLY First Year,HLY Last Year,DLY First Year,DLY Last Year,MLY First Year,MLY Last Year
6772,BARRIERE STONEHAM,QUEBEC,7010478,5205,NaN,NaN,47.17,-71.25,471000000,-711500000,597.40,1963,1976,NaN,NaN,1963.0,1976.0,1963.0,1976.0
6773,BARRIERE TOURILLI,QUEBEC,7010480,5206,NaN,NaN,47.17,-71.62,471000000,-713700000,493.80,1949,1960,NaN,NaN,1949.0,1960.0,1949.0,1960.0
6774,BEAUPORT,QUEBEC,7010565,27803,71578.0,XBO,46.84,-71.20,465013000,-711150000,10.00,1999,2025,1999.0,2024.0,1999.0,2025.0,NaN,NaN
6775,BEAUPORT,QUEBEC,7010566,5207,NaN,NaN,46.88,-71.20,465300000,-711200000,84.10,1982,1985,NaN,NaN,1982.0,1985.0,1982.0,1985.0
6776,BERTHIERVILLE,QUEBEC,7010720,5208,NaN,NaN,46.05,-73.18,460300000,-731100000,12.20,1919,1995,NaN,NaN,1919.0,1995.0,1919.0,1995.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7866,TASIUJAQ A,QUEBEC,7118366,54019,NaN,YTQ,58.67,-69.96,584004000,-695721000,36.90,2018,2025,2018.0,2024.0,2018.0,2025.0,NaN,NaN
7867,TASIUJAQ A,QUEBEC,7118369,10856,NaN,YTQ,58.67,-69.95,584016000,-695655000,36.90,1993,2015,1993.0,2015.0,NaN,NaN,NaN,NaN
7868,SALLUIT A,QUEBEC,711GG87,10226,NaN,YZG,62.18,-75.67,621055005,-754010001,227.08,1969,2015,1969.0,2015.0,NaN,NaN,NaN,NaN
7869,KANGIQSUALUJJUAQ A,QUEBEC,711L380,10684,NaN,YLU,58.71,-65.99,584227080,-655915020,66.14,1992,2015,1992.0,2015.0,NaN,NaN,NaN,NaN
7870,SUGLUK,QUEBEC,711Q2H7,6085,NaN,NaN,62.20,-75.63,621200000,-753800000,15.20,1966,1967,NaN,NaN,1966.0,1967.0,1966.0,1967.0

<h4> Put the stations on an interactive map

In [4]:
print(stnID_df['Climate ID'].nunique())
print(len(stnID_df))
stnID_df[stnID_df['Climate ID'] == '7010478']['HLY First Year'].notnull().values[0]
# if stnID_df[stnID_df['Climate ID'] == '7010478']['HLY First Year'].isna().values[0] :
#      print('Nan')

1099
1099

np.False_

In [5]:
# for feature in bars["features"]:
#     symbol = feature["properties"]["marker-symbol"]
#     coords = feature["geometry"]["coordinates"]

#     icon = AwesomeIcon(name=symbol, marker_color="red" if symbol == "bus" else "blue")
#     markers.append(Marker(icon=icon, location=(coords[1], coords[0])))

In [6]:
stn_reports = {
    'hly_dly_mly' : {
        'name' : 'HLY/DLY/MLY',
        'color' : 'purple',
    },
    'hly_dly' : {
        'name' : 'HLY/DLY',
        'color' : 'blue',
    },
    'hly_mly' : {
        'name' : 'HLY/MLY',
        'color' : 'black',
    },
    'hly' : {
        'name' : 'HLY',
        'color' : 'red',
    },
    'dly_mly' : {
        'name' : 'DLY/MLY',
        'color' : 'orange',
    },
    'mly' : {
        'name' : 'MLY',
        'color' : 'yellow',
    },
    'other' : {
        'name' : 'no reports',
        'color' : 'pink',
    },
}

stn_reports['hly_dly_mly']['name']
stn_reports['hly_dly_mly']['color']

'purple'

In [7]:
message = []
markers = []
for stn in stnID_df['Climate ID'] :
    lat = stnID_df[stnID_df['Climate ID'] == stn]['Latitude (Decimal Degrees)'].values[0]
    lon = stnID_df[stnID_df['Climate ID'] == stn]['Longitude (Decimal Degrees)'].values[0]
    
    #print(lat,lon)
    #markers.append(CircleMarker(location = (lat, lon), radius = 1, color = 'red', fill_color = 'red'))
    
    # Find availability of data
    hourly = stnID_df[stnID_df['Climate ID'] == stn]['HLY First Year'].notnull().values[0] 
    daily  = stnID_df[stnID_df['Climate ID'] == stn]['DLY First Year'].notnull().values[0] 
    monthly = stnID_df[stnID_df['Climate ID'] == stn]['MLY First Year'].notnull().values[0] 
    
    if hourly and daily and monthly :
        markers.append(CircleMarker(location = (lat, lon), radius = 1, 
                                    color = stn_reports['hly_dly_mly']['color'],
                                    fill_color = stn_reports['hly_dly_mly']['color']))
    elif hourly and daily :
        markers.append(CircleMarker(location = (lat, lon), radius = 1,
                                    color = stn_reports['hly_dly']['color'], 
                                    fill_color = stn_reports['hly_dly']['color']))
    elif hourly and monthly:
        markers.append(CircleMarker(location = (lat, lon), radius = 1,
                                    color = stn_reports['hly_mly']['color'], 
                                    fill_color = stn_reports['hly_mly']['color']))
    elif hourly :
        markers.append(CircleMarker(location = (lat, lon), radius = 1,
                                    color = stn_reports['hly']['color'], 
                                    fill_color = stn_reports['hly']['color']))
    elif daily and monthly:
        markers.append(CircleMarker(location = (lat, lon), radius = 1,
                                    color = stn_reports['dly_mly']['color'],
                                    fill_color = stn_reports['dly_mly']['color']))
    elif monthly:
        markers.append(CircleMarker(location = (lat, lon), radius = 1,
                                    color = stn_reports['mly']['color'],
                                    fill_color = stn_reports['mly']['color']))
    else:
        markers.append(CircleMarker(location = (lat, lon), radius = 1, 
                                    color = stn_reports['other']['color'], 
                                    fill_color = stn_reports['other']['color']))

    name = stnID_df[stnID_df['Climate ID'] == stn]['Name'].values[0]
    message.append(f'STN Info :\n\tname : {name}\n\tClimate ID : \n\tTC ID : \n\t')

        
# lat, lon = (62.20, -75.63)
# print(lat, lon)
# icon = AwesomeIcon(name="fa fa-circle", marker_color="gray", icon_color="darkgray")
# marker = Marker(icon=icon, location=(lat, lon))

# circle_marker = CircleMarker(location = (lat, lon), radius = 1, color = 'red', fill_color = 'red')
# circle_marker.weight = 6
# circle_marker.fillOpacity = 0

In [8]:
center = [53, -70]
zoom = 4

mapnik = basemap_to_tiles(basemaps.OpenStreetMap.Mapnik)
mapnik.base = True
mapnik.name = 'Mapnik Layer'

# toner = basemap_to_tiles(basemaps.Stamen.Toner)
# toner.base = True
# toner.name = 'Toner Layer'

bzh = basemap_to_tiles(basemaps.OpenStreetMap.BZH)
bzh.base = True
bzh.name = 'BZH layer'

grey =  basemap_to_tiles(basemaps.CartoDB.Positron)
grey.base = True
grey.name = 'Grey layer'

topo =  basemap_to_tiles(basemaps.Gaode.Satellite)
topo.base = True
topo.name = 'Topo layer'

strava =  basemap_to_tiles(basemaps.Strava.Ride)
strava.base = True
strava.name = 'Gaode layer'

m = Map(center=center, zoom=zoom, layers=[mapnik, bzh, topo, strava, grey],
        layout=Layout(width='50%', height='500px'))

m.add_control(LayersControl())

In [9]:
# marker = Marker(location=(53, -70))
# m += marker

# message1 = HTML()
# message2 = HTML()
# message1.value = "Try clicking the marker!"
# message2.value = "Hello <b>World</b>"
# message2.placeholder = "Some HTML"
# message2.description = "Some HTML"

# # Popup with a given location on the map:
# popup = Popup(
#     location=center,
#     child=message1,
#     close_button=False,
#     auto_close=False,
#     close_on_escape_key=False
# )
# m.add(popup)

# # Popup associated to a layer
# marker.popup = message2

for index, marker in enumerate(markers):
    m += marker

    message2 = HTML()
    message2.value = message[index]
    marker.popup  = message2

In [10]:
legend = LegendControl({})

# Set/Get legend title
# legend.title = "Stations Reports"  # Set title
# legend.title  # Get title

# # Set/Get legend content
# legend.legend = {}  # Set content
# legend.legend  # Get content

for report in stn_reports :
    legend.add_legend_element(stn_reports[report]['name'],stn_reports[report]['color'])  # Add a legend element
   
# legend position
legend.position = "topright"  # Set position
legend.position  # Get current position

m.add(legend)

Map(center=[53, -70], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_te…

In [11]:
m
# m
# m.add(markers[0])

m

Map(center=[53, -70], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_te…

In [12]:
m.save('test_map.html', title='My Map')

In [20]:
from IPython.display import IFrame

#IFrame(src='./test_map.html', width=1800, height=1400)
from IPython.display import IFrame, display, HTML, display_html
#display(HTML('./test_map.html', metadata=dict(isolated=True)))

#from IPython.display import HTML

#HTML(filename="./my_html_file.html")
display_html('./test_map.html')

In [22]:
```{raw} html
:file: test_map.html
```

SyntaxError: invalid syntax (379278638.py, line 1)

In [24]:
from IPython.display import IFrame
IFrame(src='./test_map.html', width=1800, height=1400)

[Link text](./test_map.html)